//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEgitimAkademi_Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientStats
    {
        public int StatsID { get; set; }
        public string SubjectText { get; set; }
        public string DescriptionText { get; set; }
        public string StatsValue { get; set; }
    }
}
