//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEgitimAkademi_Portfolio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyPortfolioDbEntities1 : DbContext
    {
        public MyPortfolioDbEntities1()
            : base("name=MyPortfolioDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> About { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Testimonial> Testimonial { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Skill> Skill { get; set; }
        public virtual DbSet<Experince> Experince { get; set; }
        public virtual DbSet<Skill2> Skill2 { get; set; }
        public virtual DbSet<Communication2> Communication2 { get; set; }
        public virtual DbSet<AdminTable> AdminTable { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Adress> Adress { get; set; }
        public virtual DbSet<SocialMedia> SocialMedia { get; set; }
        public virtual DbSet<Language> Language { get; set; }
    }
}
